export interface Book {
  id: string;
  title: string;
  author: string;
  series?: string;
  genre?: string;
  publish_date?: string; // ISO format date string
  pages?: number;
  rating: number;
  description?: string;
  review?: string;
  review_date?: string; // ISO format date string
  cover_image?: string;
  goodreads_link?: string;
  storygraph_link?: string;
  bookshop_link?: string;
  barnes_noble_link?: string;
  read_alikes_image?: string;
  created_at?: string;
  updated_at?: string;
  slug?: string; // URL-friendly version of the title
}

export interface NewBook extends Omit<Book, 'id' | 'created_at' | 'updated_at'> {
  id?: string; // Optional for new books (will be generated by Supabase)
}

export interface BookFormData extends Omit<NewBook, 'review_date'> {
  // For form handling, we might need to handle dates differently
  review_date?: string; // Format: YYYY-MM-DD
  publish_date?: string; // Format: YYYY-MM-DD
}

export type BookSortField = 'title' | 'author' | 'rating' | 'created_at' | 'review_date';
export type SortDirection = 'asc' | 'desc';

export interface BookFilters {
  genre?: string;
  author?: string;
  rating?: number;
  searchTerm?: string;
}

export interface ExternalLinks {
  goodreads?: string;
  storygraph?: string;
  bookshop?: string;
  barnesNoble?: string;
} 